controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

register:
    path: /api/register
    controller: App\Controller\UsersController::register
    methods: POST

login:
    path: /api/login
    controller: App\Controller\UsersController::login
    methods: POST

updateUser:
    path: /api/users
    controller: App\Controller\UsersController::updateUser
    methods: PUT

displayUser:
    path: /api/users
    controller: App\Controller\UsersController::displayUser
    methods: GET

disconnect:
    path: /api/disconnect
    controller: App\Controller\UsersController::disconnect
    methods: POST

getAllProducts:
    path: /api/products
    controller: App\Controller\CatalogController::getAllProducts
    methods: GET

getProduct:
    path: /api/products/{productId}
    controller: App\Controller\CatalogController::getProduct
    methods: GET
    requirements:
        productId: \d+

addProduct:
    path: /api/products
    controller: App\Controller\CatalogController::addProduct
    methods: POST

modifyProduct:
    path: /api/products/{productId}
    controller: App\Controller\CatalogController::modifyAndDeleteProduct
    methods: PUT
    requirements:
        productId: \d+

deleteProduct:
    path: /api/products/{productId}
    controller: App\Controller\CatalogController::modifyAndDeleteProduct
    methods: DELETE
    requirements:
        productId: \d+

addProductToShoppingCart:
    path: /api/carts/{productId}
    controller: App\Controller\CatalogController::addProductToShoppingCart
    methods: POST
    requirements:
        productId: \d+

removeProductFromShoppingCart:
    path: /api/carts/{productId}
    controller: App\Controller\CatalogController::removeProductFromShoppingCart
    methods: DELETE
    requirements:
        productId: \d+

getStateOfShoppingCart:
    path: /api/carts
    controller: App\Controller\CatalogController::getStateOfShoppingCart
    methods: GET

validateShoppingCart:
    path: /api/carts/validate
    controller: App\Controller\CatalogController::validateShoppingCart
    methods: POST

getAllOrdersOfUser:
    path: /api/orders
    controller: App\Controller\OrdersController::getAllOrdersOfUser
    methods: GET

getOrder:
    path: /api/orders/{orderId}
    controller: App\Controller\OrdersController::getOrder
    methods: GET
    requirements:
        orderId: \d+
